export enum Routes {
  WELCOME = 'Welcome',
  LOGIN = 'Login',
  REGISTER = 'Register',
  COMPLETE_REGISTRATION = 'CompleteRegistration',
  SUCCESSFUL_REGISTRATION = ' SuccessfulRegistration',
  SEARCH = 'Search',
  SEARCH_ADVERTS_LIST_MODE = 'SearchAdvertsListMode',
  SEARCH_ADVERTS_MAP_MODE = 'SearchAdvertsMapMode',
  FILTER_ADVERTS = 'FilterAdverts',
  NEWAD = 'NewAdd',
  HOWTOADDADVERT = 'HowToAddAdvert',
  WHOADDADVERT = 'WhoAddAdvert',
  NOTIFICATIONS = 'Notifications',
  FAVORITES = 'Favorites',
  ADVERT = 'advert',
  MANAGER_ASSISTANCE = 'ManagerAssistance',
  PROFILE = 'Profile',
  FEED = 'Feed',
  PHONE_NUMBER_CONFIRMATION = 'PhoneNumberConfirmation',
  RESTORE_ACCESS = 'RestoreAccess',
  RESTORE_ACCESS_COMPLETE = 'RestoreAccessComplete',
  HELP = 'Help',
  ABOUT_APP = 'AboutApp',
  LICENSE_AGREEMENT = 'LicenseAgreement',
  EDIT_PROFILE = 'EditProfile'
}
